### ISSUE TITLE
Approval request- web content, relaunch

### ISSUE THREAD

**Issue by evolayak** [SecretDecks/Arcana#1]
In addition to spelling and punctuation: 

1. Who & What is SecretDecks?! - 
 - How we do stuff: EDITS
 - Last paragraph: EDITS
 
2. Tarot & the Self (under construction) - SUBSTANTIVE EDITS/REWRITE

3. Founders Drop: "If we sell out all pieces, this is what we'll do with the funds": COMMENT RE: CHART

4. SD Drops
- Drop Simulation: EDITS

5. Legendary myth of "The Destruction of Civilisation": EDITS

6. Roadmap Introduction: EDITS

7. Filled in blurb for hero's journey in the Major Arcana

**Comment by DanM3rcurius** [comment]
I went over everything, looks very good!

Only thing I don't understand is this

> Founders Drop: "If we sell out all pieces, this is what we'll do with the funds": COMMENT RE: CHART

What comment?

**Comment by evolayak** [comment]
Ah! This is regarding the second chart on the founders drop page - just meant to make sure the first letter of the first word is capitalised so the format is consistent for each category in that column. (Underlined in the attached photo.)
